### ISSUE TITLE
hub: command not found

### ISSUE THREAD

**Issue by NHKK** [siph/resume-md#8]
Hi there, great repo by the way. I tried to use your repo but am encountering an issue. I don't see where you are putting the node version but when my GitHub Actions run it fails and I see the message below.
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: peaceiris/actions-gh-pages@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by siph** [comment]
Hi. Those warnings are coming from the deployment action (https://github.com/peaceiris/actions-gh-pages) and they can probably be safely ignored.

`resume-md` is actually a really simple application that just runs two CLI commands to convert the markdown to stylized HTML and PDF:
https://github.com/siph/resume-md/blob/105a14b5ae7342dc8e9850eec5d622eb008cdc11/flake.nix#L26-L33

It doesn't actually include any built-in web-servers, it just uses GitHub Actions to host the file that gets generated. Dependabot should automatically create PRs to update these actions (like this: https://github.com/siph/resume-md/pull/6), so you shouldn't need to manually update them either.

More importantly, this isn't why your build is failing. Actually, the web deployment is working fine: https://nhkk.github.io/my-resume/

You build is only failing to make a release. For some reason, the [`hub`](https://hub.github.com/) command isn't found, even though it should be installed on every github runner.

I'm not sure why. It doesn't seem like anything else is broken, but in the meantime you can still download the PDF, HTML, and MD files from the artifacts tab:
![Screenshot_20240303_112838](https://github.com/siph/resume-md/assets/6619112/6d68789c-6b7c-4ca9-bd2b-a09d41a0a7ec)

**Comment by NHKK** [comment]
Thank you so much.
